Added comments to classes
GlebEmelianov/Gleb_Emelianov_Zoo pull request #1
Opened 2022-05-05 19:41 UTC by GlebEmelianov

2022-05-08 15:16 UTC, Fulcrum81 requested changes
Conceptually: Can I create a Lion in this program that meows, breathes water and flies? I think I can, but I shouldn't be able to do that.
The certain animals should also be implemented as classes so that their actions are predefined and cannot be changed.
If you have need any additional clarification please feel free to ask

2022-05-08 15:16 UTC, Fulcrum81 commented on src/main/java/zoo/Bird.java
> +    public String getAction() {return action;};
Unnecessary ";" after a curly brace, please remove

2022-05-08 15:16 UTC, Fulcrum81 commented on src/main/java/zoo/Bird.java
> +    public String getNameOfFish() {return nameOfBird;};
Unnecessary ";" after a curly brace, please remove

2022-05-08 15:16 UTC, Fulcrum81 commented on src/main/java/zoo/Fish.java
> +    public String getAction() {return action;};
Unnecessary ";" after a curly brace, please remove

2022-05-08 15:16 UTC, Fulcrum81 commented on src/main/java/zoo/Fish.java
> +    public String getNameOfFish() {return nameOfFish;};
Unnecessary ";" after a curly brace, please remove

2022-05-08 15:16 UTC, Fulcrum81 commented on src/main/java/zoo/Main.java
> +        Mammal Lion = new Mammal("Lion", "roars", "earth", "air");
Here and below: remember the naming conventions, this is just a variable, the name should be in camelCase

2022-05-10 19:13 UTC, GlebEmelianov commented
> Conceptually: Can I create a Lion in this program that meows, breathes water and flies? I think I can, but I shouldn't be able to do that. The certain animals should also be implemented as classes so that their actions are predefined and cannot be changed. If you have need any additional clarification please feel free to ask

Added classes for each animal with their unique sound

2022-05-16 17:46 UTC, GlebEmelianov commented
Made changes in Zoo code. Added test frameworks and XML files for TestNG

2022-08-03 16:59 UTC, merged